import {
  FileCodeIcon,
  AtomIcon,
  LightningIcon,
  FileJsIcon, 
  DatabaseIcon,
  CloudArrowUpIcon,
  GitBranchIcon,
  TerminalIcon,
  BrainIcon,
  LightbulbIcon,
  TargetIcon
} from "@phosphor-icons/react";
import { SkillItem, CategoryMeta } from "../@types";

export const CATEGORY_META: Record<string, CategoryMeta> = {
    Frontend: {
        label: "Frontend & UI",
        color: "#38bdf8",
        description: "Interfaces responsivas, acessíveis e altamente performáticas.",
    },
    "Backend & Dados": {
        label: "Backend & Dados",
        color: "#34d399",
        description: "APIs robustas, modelagem de dados e arquitetura de servidores.",
    },
    "Infra & DevOps": {
        label: "Infra & DevOps",
        color: "#fbbf24",
        description: "Ambientes containerizados, automação e ferramentas de build.",
    },
    "IA & Produtividade": {
        label: "IA & Produtividade",
        color: "#f472b6",
        description: "Engenharia de prompts, automação de fluxo e eficiência pessoal.",
    },
    "Soft Skills & Métodos": {
        label: "Soft Skills & Métodos",
        color: "#a78bfa",
        description: "Abordagem mental, consistência de entrega e aprendizado contínuo.",
    },
};

export const SKILLS_DATA: SkillItem[] = [
    {
        id: "ts",
        name: "TypeScript",
        category: "Frontend",
        icon: FileCodeIcon,
        desc: "Segurança de tipos em tempo de compilação para aplicações escaláveis.",
        level: "Sólido",
        sinceYear: 2022,
        useCase: "Desenvolvimento de SaaS, interfaces complexas em React e padronização de contratos de API.",
        whyILike: "Elimina toda uma classe de bugs em produção antes mesmo de o código ser executado. O autocompletar e a refatoração segura mudam o patamar do desenvolvimento.",
        codeSnippet: `interface ProjectPayload {\n  id: string;\n  title: string;\n  tags: string[];\n  publishedAt: Date;\n}\n\nexport const formatProject = (item: ProjectPayload): string => {\n  return \`[\${item.publishedAt.getFullYear()}] \${item.title}\`;\n};`,
        relatedSkillIds: ["react", "node"],
        searchQuery: "typescript",
    },
    {
        id: "react",
        name: "React & Next.js",
        category: "Frontend",
        icon: AtomIcon,
        desc: "Criação de componentes reutilizáveis e arquitetura baseada em estado.",
        level: "Sólido",
        sinceYear: 2021,
        useCase: "Construção de SPAs modernas, dashboards interativos e aplicações web reativas.",
        whyILike: "A flexibilidade do ecossistema e o modelo mental baseado em componentes tornam a UI previsível e extremamente modular.",
        codeSnippet: `import { useState } from 'react';\n\nexport function useCounter(initial = 0) {\n  const [count, setCount] = useState(initial);\n  const increment = () => setCount(prev => prev + 1);\n  return { count, increment };\n}`,
        relatedSkillIds: ["ts", "vite"],
        searchQuery: "react",
    },
    {
        id: "vite",
        name: "Vite",
        category: "Frontend",
        icon: LightningIcon,
        desc: "Empacotador e ferramenta de build de altíssima performance para frontend.",
        level: "Sólido",
        sinceYear: 2023,
        useCase: "Configuração e aceleração de ambientes de desenvolvimento SPA e landing pages.",
        whyILike: "O Hot Module Replacement (HMR) instantâneo transforma o fluxo de desenvolvimento em algo incrivelmente ágil e sem fricção.",
        codeSnippet: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 3000, open: true }\n});`,
        relatedSkillIds: ["react", "ts"],
        searchQuery: "vite",
    },
    {
        id: "node",
        name: "Node.js & Express",
        category: "Backend & Dados",
        icon: FileJsIcon,
        desc: "Ambiente de execução JavaScript no servidor para APIs RESTful.",
        level: "Intermediário",
        sinceYear: 2021,
        useCase: "Desenvolvimento de backends leves, microsserviços e automações web.",
        whyILike: "Permite usar a mesma linguagem (TypeScript) no cliente e no servidor, unificando o fluxo de raciocínio lógico.",
        codeSnippet: `import express from 'express';\n\nconst app = express();\napp.use(express.json());\n\napp.get('/health', (req, res) => {\n  res.status(200).json({ status: 'UP', timestamp: new Date() });\n});`,
        relatedSkillIds: ["ts", "postgresql"],
        searchQuery: "node",
    },
    {
        id: "postgresql",
        name: "PostgreSQL",
        category: "Backend & Dados",
        icon: DatabaseIcon,
        desc: "Banco de dados relacional robusto com forte integridade estrutural.",
        level: "Intermediário",
        sinceYear: 2022,
        useCase: "Modelagem de dados relacionais para sistemas SaaS e persistência segura de usuários.",
        whyILike: "Garantia de transações ACID e flexibilidade para consultas complexas utilizando SQL puro ou ORMs.",
        codeSnippet: `CREATE TABLE users (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  email VARCHAR(255) UNIQUE NOT NULL,\n  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP\n);`,
        relatedSkillIds: ["node"],
        searchQuery: "postgres",
    },
    {
        id: "docker",
        name: "Docker",
        category: "Infra & DevOps",
        icon: CloudArrowUpIcon,
        desc: "Containerização de aplicações para isolamento e portabilidade.",
        level: "Intermediário",
        sinceYear: 2022,
        useCase: "Padronização de ambientes de desenvolvimento e deploy de aplicações full stack.",
        whyILike: "Acaba com o clássico problema de compatibilidade de ambiente. Garante que o servidor de produção seja idêntico ao local.",
        codeSnippet: `FROM node:18-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . . \nEXPOSE 3000\nCMD ["npm", "start"]`,
        relatedSkillIds: ["node"],
        searchQuery: "docker",
    },
    {
        id: "git",
        name: "Git & GitHub",
        category: "Infra & DevOps",
        icon: GitBranchIcon,
        desc: "Controle de versão distribuído e colaboração em equipe.",
        level: "Sólido",
        sinceYear: 2020,
        useCase: "Versionamento de código fonte, controle de branches e histórico de engenharia.",
        whyILike: "A segurança de saber que qualquer alteração pode ser rastreada, revertida ou testada em branches isoladas.",
        codeSnippet: `git checkout -b feature/refactor-architecture\ngit add .\ngit commit -m "refactor: migrate data structures to constants and types"\ngit push origin feature/refactor-architecture`,
        relatedSkillIds: ["ts", "vite"],
        searchQuery: "git",
    },
    {
        id: "terminalIcon",
        name: "CLI & Shell Script",
        category: "Infra & DevOps",
        icon: TerminalIcon,
        desc: "Automação de tarefas e manipulação eficiente via linha de comando.",
        level: "Sólido",
        sinceYear: 2020,
        useCase: "Criação de scripts utilitários, automação de builds e gerenciamento de processos.",
        whyILike: "Velocidade incomparável na execução de tarefas repetitivas e controle total sobre o ambiente de trabalho.",
        codeSnippet: `#!/bin/bash\necho "Iniciando build de produção..."\nnpm run build\necho "Build concluído com sucesso [OK]!"`,
        relatedSkillIds: ["git", "docker"],
        searchQuery: "shell",
    },
    {
        id: "ai-prompt",
        name: "Engenharia de Prompts & IA",
        category: "IA & Produtividade",
        icon: BrainIcon,
        desc: "Uso estratégico de IA como copiloto de desenvolvimento, refatoração e arquitetura.",
        level: "Sólido",
        sinceYear: 2023,
        useCase: "Aceleração de MVPs, depuração de erros complexos, planejamento de arquitetura e geração de testes.",
        whyILike: "Multiplica a capacidade de entrega individual, permitindo focar na lógica de negócio principal e na experiência do usuário.",
        codeSnippet: `// Prompt estruturado para arquitetura\n// "Atue como Arquiteto Sênior React/TS. Proponha um hook modular para gerenciar estado assíncrono com tratamento de loading, erro e cache em memória."`,
        relatedSkillIds: ["ts", "react"],
        searchQuery: "ai",
    },
    {
        id: "continuous-learning",
        name: "Aprendizado Contínuo (Inglês Técnico)",
        category: "Soft Skills & Métodos",
        icon: LightbulbIcon,
        desc: "Busca constante por evolução técnica através de documentações internacionais e estudos.",
        level: "Sólido",
        sinceYear: 2020,
        useCase: "Consumo de documentações oficiais em inglês, artigos de engenharia de ponta e resolução rápida de problemas.",
        whyILike: "O acesso imediato à fonte primária de conhecimento tecnológico acelera drasticamente a curva de aprendizado.",
        codeSnippet: `// Input compreensivo diário:\n// 1. Ler RFCs e Release Notes de frameworks.\n// 2. Praticar escuta ativa em podcasts de arquitetura de software.`,
        relatedSkillIds: ["ts"],
        searchQuery: "learning",
    },
    {
        id: "micro-tasks",
        name: "Produtividade por Micro-tarefas",
        category: "Soft Skills & Métodos",
        icon: TargetIcon,
        desc: "Metodologia de divisão de grandes problemas em blocos de 15 a 30 minutos.",
        level: "Especialista",
        sinceYear: 2021,
        useCase: "Manutenção de foco contínuo, eliminação de procrastinação e consistência diária em projetos SaaS.",
        whyILike: "Transforma projetos complexos e assustadores em pequenas vitórias diárias acumuladas.",
        codeSnippet: `// Sprint Pessoal de 30min:\n// [ ] 10m - Modelagem de tipos\n// [ ] 15m - Implementação da UI\n// [ ] 05m - Teste rápido`,
        relatedSkillIds: ["git"],
        searchQuery: "productivity",
    }
];